baseURL = "/"
languageCode = "zh-cn"
title = "Mu Xin"
theme = "blackburn"
author = "mx_in"
	
copyright = "Copyright 2017 mx_in"
canonifyurls = true
paginate = 7

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Thinking / Wirting / Programming"
  brand = "  Mx-In"
  googleAnalytics = "Your Google Analytics tracking ID"
 # disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "ocean"
  dateFormat = "02 Jan 2006"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone-square fa-fw'></i>"
    weight = 6
    identifier = "contact"
    url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # Techie
  github = "mx-in"
